### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by canerelci** [inorganik/countUp.js-angular2#10]
```
[ ] Bug
[X] Build issue
[ ] Feature request
```

#### Version info 

```
Angular:
Angular CLI: 6.0.3
countup.js-angular2: 6.0.0
```

#### Description
Just updated to new version to get rid of previous packaging errors but it seems this one has its own issue. 

`ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/countup.js-angular2/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

I removed node_modules from countup.js-angular2 folder and it's okay now. Anyway, you better check it out.

**Comment by inorganik** [comment]
Hi, I just bumped the version to 6.0.1 to fix a bug and republished the package. Could you please try updating and let me know if this issue persists? If so I'll reopen. Thanks.

I'm not sure how a node_modules folder got generated inside the countup.js-angular2 folder. I could not reproduce this issue, on either Angular 6.0.0 or 6.0.4.

**Comment by ryanrain** [comment]
$ node -v
v8.9.4

Thanks Jamie!
