### ISSUE TITLE
End value is overflowed when greater than 999

### ISSUE THREAD

**Issue by Hrafven** [inorganik/countUp.js-angular2#11]
```
[x] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 

```
Angular: 5.2.10
Angular CLI: 6.0.7
countup.js-angular2: 6.0.0
```

#### Description

Hi @inorganik,

I am having an issue when endVal is greater than 999 (looks like it is related to #9 )
When the value is greater than 999, it goes up to 100 more, then down to endVal.

Example:
Here is the code I have used :
```html
<span [endVal]="1100">0</span>
```
Here is what it does :
![countup](https://user-images.githubusercontent.com/15106129/41040826-c8589f94-699d-11e8-822e-a0955bc5b586.gif)

I am expecting it to stop exactly at the provided value.

Thanks.

**Comment by inorganik** [comment]
This is now fixed in v6.0.1
