### ISSUE TITLE
feature request - disable animation on first load

### ISSUE THREAD

**Issue by akhatri** [inorganik/countUp.js-angular2#13]
```
[ ] Bug
[ ] Build issue
[X ] Feature request
```

#### Version info 

```
Angular: 5
Angular CLI: Ionic based 3.9.2
countup.js-angular2:  6.0.0
```

#### Description

Thanks for this great plugin. It really helps in creating a delightful user experience. I was hoping we could get a feature where the animation doesnt happen on first load? I have a couter for my basketball game that adds/subtracts 10 at a go. On the first load I don't want it to animate though, I only want it to animate when it actually changes.

`            <span countUp [endVal]="baskets" duration="0.450">{{baskets}}</span>`

**Comment by inorganik** [comment]
Sure that's easy. Just set the initial `endVal` to the same as the `startVal`, probably 0. 

As long as you have brackets around `[endVal]`, it will bind to your `baskets` property, and whenever that changes, it will count to that number. Happy coding!
