### ISSUE TITLE
Support for Angular 7

### ISSUE THREAD

**Issue by agil-NUBBA** [inorganik/countUp.js-angular2#16]
```
[x] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 

```
Angular: 7.0.0
Angular CLI: 7.0.1
countup.js-angular2: ^6.0.1
```

#### Description

`ng serve` on Angular 7 fails due to:

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/countup.js-angular2/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

**Comment by inorganik** [comment]
Ok. Just pushed 6.0.2 of this lib and tested it in a new Angular 7 project and it works 🎉

**Comment by agil-NUBBA** [comment]
Hi,

Thanks, now works again. Could you extend the peer dependencies to avoid the warning?

```
npm WARN countup.js-angular2@6.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN countup.js-angular2@6.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by inorganik** [comment]
What you could do is change it in `node_modules/countup.js-angular2/projects/count-up/package.json` to be v7:

```
"peerDependencies": {
    "@angular/common": "^7.0.0-rc.0 || ^7.0.0",
    "@angular/core": "^7.0.0-rc.0 || ^7.0.0"
  },
```
If I made the change here it would break for a lot of angular 6 users.

**Comment by agil-NUBBA** [comment]
As far as know it is posible to suport both, ngx-ui-switch did this on https://github.com/webcat12345/ngx-ui-switch/commit/e37de190a6e360c6005177a57bca7a3ce0d5560e, can't tell if it would be that easy.

Maybe this afternoon I can try to PR this.
