### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by ljmcadenas** [inorganik/countUp.js-angular2#2]
Hi!

First of all, thanks for your code!
I believe that an animate callback would be useful.

Think about it ;)

Thanks again!
PD: Sorry for my english ;)

**Comment by choopage** [comment]
What do you mean? Are you saying that it is useful to have alert callback on complete?

**Comment by choopage** [comment]
Oh this is a great idea too to have a callback for every animation frame.

It would be great to also have a callback or event emitter On Complete.

**Comment by inorganik** [comment]
If you need a callback for every animation frame, consider using `requestAnimationFrame()`
