### ISSUE TITLE
Incorrect condition check

### ISSUE THREAD

**Issue by emn178** [inorganik/countUp.js-angular2#23]
https://github.com/inorganik/countUp.js-angular2/blob/a569c20a80ced61ea29cde806bc8f6d6235fb7ba/projects/count-up/src/lib/count-up.directive.ts#L37

It won't work if `[endVal]="0"`

**Comment by inorganik** [comment]
good call, I'll push up a fix sometime soon.

**Comment by inorganik** [comment]
Fixed in 7.1
