### ISSUE TITLE
start a new countup while the old one did not finish problem

### ISSUE THREAD

**Issue by MUYUSY** [inorganik/countUp.js-angular2#26]
```
[x ] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 
all version.

```
Angular:
Angular CLI:
countup.js-angular2: 
```

#### Description
https://stackblitz.com/edit/angular-countup

first countUp afterViewInit with duration 2s, after that change the duration to 30, and every 30s make the endVal increase 10, which make the countUp looks like always increasing.

button "view1" and "view2" changes the startVal and reset the progress.

the problem is after the countUp start of duration 30s, while the number is increasing, click button "view2",  we will see the problem, the number first countUp to 3000 in 2s, and then continue the last countUp to 1010.

[fix suggestion]
I can not create a pull request, so I give my solution here.
modify ngOnChanges function as follow:
```
ngOnChanges(changes: SimpleChanges) {
      if (changes.options && (changes.options.currentValue !== changes.options.priviousValue)) {
          if (this.countUp)
              this.countUp.reset();
          this.countUp = new CountUp(this.el.nativeElement, this.endVal,this.options);
          this.countUp.start(() => {
              this.complete.emit();
          });
      } else if (changes.endVal && !changes.endVal.firstChange) {
          if (this.previousEndVal != undefined) {
              this.options = {
                  ...this.options,
                  startVal: this.previousEndVal
              };
          }
          this.countUp.update(this.endVal);
          this.previousEndVal = this.endVal;
      }
  }
```

**Comment by inorganik** [comment]
Well this did make me discover a bug in the way I handled ngOnChanges - so I pushed a patch - `7.1.1`. 

If you want to keep updating CountUp, you can do so just by updating the value you pass:

app.component.ts:
```

https://stackblitz.com/edit/angular-countup-eygnty

**Comment by MUYUSY** [comment]
> Well this did make me discover a bug in the way I handled ngOnChanges - so I pushed a patch - `7.1.1`.
> 
> If you want to keep updating CountUp, you can do so just by updating the value you pass:
> 
> app.component.ts:
> 
> ```
>   newNum = 10;
>   options = {
>     useEasing: false,
>     duration: 3
>   }
> 
>   update() {
>     this.newNum += 10;
>     console.log('update', this.newNum);
>   }
> ```
> app.component.html:
> 
> ```
> <h2 [countUp]="newNum" [reanimateOnClick]="false" [options]="options" (complete)="update()"></h2>
> ```
> https://stackblitz.com/edit/angular-countup-eygnty

Thanks very much, I got it. But mention that this can only use with the patch after 7.1, since I was using 7.0 which did not support.

**Comment by inorganik** [comment]
Yep, that ability was added in 7.1 (due to another issue). If you issue is resolved, can this be closed?

**Comment by MUYUSY** [comment]
Yep, thanks a lot.
