### ISSUE TITLE
Error on import module to test in Jest

### ISSUE THREAD

**Issue by ramonferreiradev** [inorganik/countUp.js-angular2#28]
```
[X] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 

```
Angular: 7
Angular CLI: 7.3.1
countup.js-angular2:  7.1.1
Jest: 24.5.0
```

#### Description

Hi, I'm having an issue to run tests with Jest in a component that I'm using the lib. The error log from Jest is described below. Can you help me? Thanks. 

src/app/components/limit-bar/limit-bar.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper"
config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Development\neon-pj\node_modules\countup.js\dist\countUp.min.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){var __assign=this&&this.__assign||function(){return(__assign=Object.assign||function(t){for(var i,a=1,s=arguments.length;a<s;a++)for(var n in i=arguments[a])Object.prototype.hasOwnProperty.call(i,n)&&(t[n]=i[n]);return t}).apply(this,arguments)},CountUp=function(){function t(t,i,a){var s=this;this.target=t,this.endVal=i,this.options=a,this.version="2.0.4",this.defaults={startVal:0,decimalPlaces:0,duration:2,useEasing:!0,useGrouping:!0,smartEasingThreshold:999,smartEasingAmount:333,separator:",",decimal:".",prefix:"",suffix:""},this.finalEndVal=null,this.useEasing=!0,this.countDown=!1,this.error="",this.startVal=0,this.paused=!0,this.count=function(t){s.startTime||(s.startTime=t);var i=t-s.startTime;s.remaining=s.duration-i,s.useEasing?s.countDown?s.frameVal=s.startVal-s.easingFn(i,0,s.startVal-s.endVal,s.duration):s.frameVal=s.easingFn(i,s.startVal,s.e

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:451:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous>.__assign (node_modules/countup.js-angular2/bundles/countup.js-angular2.umd.js:2:111)
      at Object.<anonymous> (node_modules/countup.js-angular2/bundles/countup.js-angular2.umd.js:5:2)

**Comment by inorganik** [comment]
First make sure you are ignoring `node_modules` in your jest config:

jest.config.js
```
module.exports = {
  ...
  transformIgnorePatterns: ['node_modules/(?!(jest-test))'],
};
```
In the spec file for the component, import CountUpModule:
```
TestBed.configureTestingModule({
  imports: [ CountUpModule ]
})
```
That should do it, hopefully that resolves your issue

**Comment by ramonferreiradev** [comment]
Hi, Jamie.

I tried this config but doesn't work. The Jest continues logging the same error. 

Below my package.json where is the Jest configuration

{
  ...
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "jest --no-cache --coverage",
    "tdd": "jest --no-cache --coverage --watch",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build": "ng build",
    "commit": "git-cz"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.4",
    "@angular/common": "~7.2.4",
    "@angular/compiler": "~7.2.4",
    "@angular/core": "~7.2.4",
    "@angular/elements": "^7.2.4",
    "@angular/forms": "~7.2.4",
    "@angular/platform-browser": "~7.2.4",
    "@angular/platform-browser-dynamic": "~7.2.4",
    "@angular/router": "~7.2.4",
    "@webcomponents/custom-elements": "^1.2.1",
    "@webcomponents/webcomponentsjs": "^2.2.7",
    "core-js": "^2.6.4",
    "countup.js-angular2": "^7.1.1",
    "document-register-element": "^1.13.1",
    "ng-lottie": "^0.3.2",
    "rxjs": "~6.4.0",
    "tiny-slider": "^2.9.1",
    "tslib": "^1.9.3",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^7.3.1",
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "^7.3.1",
    "@angular/compiler-cli": "^7.2.7",
    "@angular/language-service": "~7.2.4",
    "@commitlint/cli": "^7.5.2",
    "@commitlint/config-conventional": "^7.5.0",
    "@types/jest": "^24.0.11",
    "@types/node": "~10.12.24",
    "@whizark/cz-cli": "^0.7.0",
    "codelyzer": "~4.5.0",
    "commitizen": "^3.0.7",
    "concat": "^1.0.3",
    "cz-conventional-changelog": "^2.1.0",
    "fs-extra": "^7.0.1",
    "git-cz": "^3.0.1",
    "husky": "^1.3.1",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.5.0",
    "jest-preset-angular": "^6.0.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.0.2",
    "tslint": "~5.12.1",
    "typescript": "3.2.4"
  },
  "jest": {
    "verbose": true,
    "coverageDirectory": "dist/test-coverage",
    "collectCoverageFrom": [
      "**/*.ts"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|angular2-ui-switch|ng-dynamic)",
      "node_modules/(?!(jest-test))"
    ],
    "globals": {
      "ts-jest": {
        "tsConfigFile": "./tsconfig.spec.json"
      },
      "__TRANSFORM_HTML__": true
    },
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/src/setupJest.ts"
    ]
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
}

**Comment by inorganik** [comment]
I was able to reproduce, I'll see what I can figure out

**Comment by inorganik** [comment]
Ok, I got it working. Also I pushed up my changes in the test app included in this repo, so it has a passing test with Jest, as well as a new section in the README. 

For Jest, make sure you have the following in your jest.config.js:
```
transform: {
  '^.+\\.(js|ts|tsx)$': 'ts-jest'
},
transformIgnorePatterns: ['node_modules/(?!countup.js)']
```

**Comment by ramonferreiradev** [comment]
Hi Jamie

It works!!!

The only change I had to make was to remove the "transform". For some reason, Jest continued to receive an error if this setting was set.

Thank you for your help.
Regards.
