### ISSUE TITLE
How to reset countup js?

### ISSUE THREAD

**Issue by lreiner** [inorganik/countUp.js-angular2#29]
Hi I have a small issue. How can I reset count up js? 

At the moment I just use html to use count up js and pass options to it. Like this:

```
<h1 id=“exampleID“ [countUp]="myEndVal" [options]="myOpts">0</h1>
```

But how can I reset it all to zero? StartVal, EndVal etc.?

**Comment by inorganik** [comment]
Set `myEndVal` to zero - that's it.

**Comment by inorganik** [comment]
closing, but if this didn't answer your question, feel free to chime in
