### ISSUE TITLE
 Extend peer dependencies to Angular 8

### ISSUE THREAD

**Issue by alvaro-octal** [inorganik/countUp.js-angular2#32]
**Issue description**

running `npm install` throws the following warning:

```
npm WARN countup.js-angular2@7.2.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN countup.js-angular2@7.2.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 8

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by inorganik** [comment]
That was fast! Angular 8 just dropped yesterday :)

I'll make an update.

**Comment by inorganik** [comment]
Peer deps extended to include ng 8 in [v7.3.0](https://github.com/inorganik/countUp.js-angular2/releases/tag/7.3.0)
