### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Sparker73** [inorganik/countUp.js-angular2#33]
```
[x] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 

ng --version
```
Angular CLI: 8.3.4
Node: 10.15.0
OS: darwin x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.4
@angular-devkit/build-angular      0.803.4
@angular-devkit/build-optimizer    0.803.4
@angular-devkit/build-webpack      0.803.4
@angular-devkit/core               8.3.4
@angular-devkit/schematics         8.3.4
@angular/cdk                       8.2.0
@angular/cli                       8.3.4
@angular/flex-layout               8.0.0-beta.27
@angular/http                      7.2.15
@angular/material                  8.2.0
@angular/material-moment-adapter   8.2.0
@ngtools/webpack                   8.3.4
@schematics/angular                8.3.4
@schematics/update                 0.803.4
rxjs                               6.5.3
typescript                         3.4.2
webpack                            4.40.2
```
package.json (dependencies & devDependencies)
```
"dependencies": {
  "@angular/animations": "^8.2.6",
  "@angular/cdk": "^8.2.0",
  "@angular/common": "^8.2.6",
  "@angular/compiler": "^8.2.6",
  "@angular/core": "^8.2.6",
  "@angular/flex-layout": "^8.0.0-beta.27",
  "@angular/forms": "^8.2.6",
  "@angular/http": "^7.2.15",
  "@angular/material": "^8.2.0",
  "@angular/material-moment-adapter": "^8.2.0",
  "@angular/platform-browser": "^8.2.6",
  "@angular/platform-browser-dynamic": "^8.2.6",
  "@angular/router": "^8.2.6",
  "@candidosales/material-time-picker": "^2.0.0",
  "@ngrx/effects": "^8.3.0",
  "@ngrx/router-store": "^8.3.0",
  "@ngrx/store": "^8.3.0",
  "@swimlane/ngx-charts": "^12.0.1",
  "bootstrap": "^4.3.1",
  "bowser": "^2.6.1",
  "chart.js": "^2.8.0",
  "cleave.js": "^1.5.3",
  "core-js": "^3.2.1",
  "countup.js-angular2": "^7.3.0",
  "d3": "^5.12.0",
  "font-awesome": "^4.7.0",
  "hammerjs": "^2.0.8",
  "highcharts": "^7.2.0",
  "lodash": "^4.17.15",
  "moment": "^2.24.0",
  "ng-html-util": "2.0.x",
  "ng2-nouislider": "1.5.2",
  "ngrx-store-freeze": "^0.2.4",
  "ngx-cleave-directive": "^1.1.3",
  "ngx-image-cropper": "^1.4.1",
  "nouislider": "^9.0.0",
  "oidc-client": "^1.9.1",
  "rxjs": "^6.5.3",
  "sweetalert2": "8.17.1",
  "terraformer-wkt-parser": "^1.2.0",
  "terser": "4.3.1",
  "tslib": "^1.10.0",
  "web-animations-js": "^2.3.2",
  "zone.js": "^0.10.2"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^0.803.4",
  "@angular-devkit/schematics": "^8.3.4",
  "@angular/cli": "^8.3.4",
  "@angular/compiler-cli": "^8.2.6",
  "@angular/language-service": "^8.2.6",
  "@ngrx/schematics": "^8.3.0",
  "@ngrx/store-devtools": "^8.3.0",
  "@types/googlemaps": "^3.37.6",
  "@types/hammerjs": "^2.0.36",
  "@types/jasmine": "^3.4.0",
  "@types/jasminewd2": "~2.0.6",
  "@types/lodash": "^4.14.138",
  "@types/node": "^12.7.5",
  "codelyzer": "^5.1.0",
  "jasmine-core": "^3.4.0",
  "jasmine-spec-reporter": "^4.2.1",
  "karma": "^4.3.0",
  "karma-chrome-launcher": "^3.1.0",
  "karma-cli": "^2.0.0",
  "karma-coverage-istanbul-reporter": "^2.1.0",
  "karma-jasmine": "^2.0.1",
  "karma-jasmine-html-reporter": "^1.4.2",
  "protractor": "^5.4.2",
  "rxjs-tslint": "^0.1.7",
  "ts-node": "^8.3.0",
  "tslint": "^5.20.0",
  "typescript": "3.4.2",
  "webdriver-manager": "^12.1.6",
  "webpack": "^4.40.2"
}
```

#### Description

The last line of the CountUp.js library after bundled into "scripts.js" has this token export:
```
export { CountUp };
```
This error came after I upgraded all dependencies in the project including CountUp.js.

The serve and build commands don't report any error and says the build is ok. It seems the functionality isn't affected, it is only reported at runtime every time a reload the App while serving the project locally with `ng serve`, by the way this is almost the first output I get on the console.

I have checked-in the [x] Bug option but not sure of the implications, is only a syntax error after all.

I haven't tried what happens in production and not sure if it is safe to go to production or if I go back to a previos version. Any suggestion?

**Comment by inorganik** [comment]
I'm wondering what you mean by this:

> The last line of the CountUp.js library after bundled into "scripts.js"

scripts.js?

**Comment by Sparker73** [comment]
On Sep 20, 2019, at 16:51, Jamie Perkins <notifications@github.com> wrote:

I'm wondering what you mean by this:

The last line of the CountUp.js library after bundled into "scripts.js"

scripts.js?

**Comment by Sparker73** [comment]
![countup js](https://user-images.githubusercontent.com/9856898/65361204-53f4b900-dbc8-11e9-9172-58b3bb2c36f9.png)
There, in the bundle file **scripts.js** is CountUp.js, it looks like was the first library minified in this bundle. The browser console reports the error with a link to the code like in the attached image. I wish I could be more useful, and again, everything works ok but I don't know the real implications if any.

**Comment by inorganik** [comment]
Thanks for clarifying. I wasn't able to reproduce until I included CountUp.js in scripts in angular.json. But you shouldn't have to do anything with scripts. Just include the CountUpModule as described in the README, it already has CountUp.js bundled as a dependency and you won't have this issue (at least I didn't in my test builds).

**Comment by inorganik** [comment]
That is a really nice looking page btw :)

**Comment by Sparker73** [comment]
Oh excellent, it means that when I upgraded the dependency I kept doing that import the old way, my bad. Thanks for the tip, I will close this issue. The page has being evolving from some ugly face thing back in 2017 till now, I have learned a lot in the process. Have a good day and many many thanks for your help.

**Comment by inorganik** [comment]
In case anyone runs into this error and finds this issue, here's some info. It's caused by ES6 modules... this package was using an es6 packaged version of CountUp.js. In the latest patch, `v7.3.2`, it imports from a UMD packaged version of CountUp.js which should resolve this error.
