### ISSUE TITLE
Start animation when element is scrolled or is visible in viewport

### ISSUE THREAD

**Issue by khanSufiyan** [inorganik/countUp.js-angular2#35]
Hi, I am trying to call the animation when the element is scrolled to or is visible in the viewport. Is there any way to achieve this?

**Comment by anna-werner** [comment]
I have the same problem and can't find a solution. Javascript detecting the windows scroll position doesn't seen to work. Are there any solutions?

**Comment by inorganik** [comment]
You have to use a scroll spy - I made [this one](https://gist.github.com/inorganik/a9b3ac67cb1f6a38fcfdc0d7c12047b0) for a separate project. It's not bulletproof, but it's pretty good. You could use it like this:

```html
<h1 [countUp]="myEndVal"  appScrollSpy [inView]="true" [emitTrueOnce]="true" (scrollSpy)="setCountUp()"></h1>
```
Then in your component:
```ts
setCountUp() {
  this.myEndVal = 345; // whatever number you want to count to
}
```
This is what it's doing: the scroll spy directive is using the option `inView` - it emits when the element is in view, the event `(scrollSpy)` is handled by a `setCountUp()` method - all it does is set a value to `myEndVal`. The countUp directive automatically defers animation until you set an end val.

**Comment by inorganik** [comment]
Going to go ahead and close this, hopefully the scroll spy solves your issues
