### ISSUE TITLE
how can i add the special character like '+', '-'?

### ISSUE THREAD

**Issue by ninjadev1030** [inorganik/countUp.js-angular2#7]
I saw the angular2 demo.
hmm, it has the function to add the special character like `+`, `-`, and others.
but it was not shown in the code.
so i'd like to get that function(adding special character).
please suggest your ideas.

#### Version info 

```
Angular:
Angular CLI:
countup.js-angular2: 
```

**Comment by inorganik** [comment]
could you give me an example? Like do you want it to count prefixed with a plus like `+25`?

**Comment by ninjadev1030** [comment]
@inorganik 
I mean like this `50+`

**Comment by inorganik** [comment]
In the demo, it shows how to use all the options, including suffix which is a string appended to the end of number. The options object is passed to the countUp attribute:

```html
<h1 [countUp]="{ suffix: '+' }" endVal="345">0</h1>
```

**Comment by ninjadev1030** [comment]
@inorganik 
okay. it was solved. thanks. 👍
